apiVersion: apps/v1
kind: Deployment
metadata:
  name: radio
  labels:
    app: radio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radio
  template:
    metadata:
      labels:
        app: radio
    spec:
      containers:
        - name: radio
          image: registry.gitlab.com/centos/automotive/sample-images/demo/auto-apps:latest
          command:
          - /usr/bin/radio-service
          volumeMounts:
            - name: vsomeip
              mountPath: /run/vsomeip
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: vsomeip
          persistentVolumeClaim:
            claimName: some-ip-volume-claim
